### ISSUE TITLE
關於underscore源碼中提到了25個扩展方法之疑問？

### ISSUE THREAD

**Issue by wangdabaoqq** [hanzichi/underscore-analysis#34]
我在拜讀您整體的underscore源碼中提到了`数组或者对象的扩展方法 共 25 个扩展方法`．我覺得對於其中的一些方法不是已經存在了嗎？
那麼重寫的原因是在出underscore.js之前瀏覽器不支持es5的一些方法嗎?

**Comment by lessfish** [comment]
对，低版本 ie，可以把他想像成一个 polyfill

而且有的方法，underscore 封装给了 Object 和 Array 使用，原生的 es5 可能只有 Array 有

**Comment by wangdabaoqq** [comment]
那我明白了，谢谢您的回答。
